swagger: '2.0'
info:
  description: This is example descripton of our documentation in Swagger.
  version: 1.0.5
  title: Car
paths:
  /all-car/:
    get:
      summary: List all car
      operationId: listCar
      tags:
        - car
      responses:
        '200':
          description: A paged array of car
          schema:
            $ref: '#/definitions/CarListDTO'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/Error'
  /create-car/:
    post:
      summary: create car
      operationId: createCar
      tags:
        - car
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: operation name
          required: true
          schema:
            $ref: '#/definitions/CarDTO'
      responses:
        '200':
          description: A paged array of car
          schema:
            $ref: '#/definitions/CarDTO'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/Error'

  /car/{id}/:
    get:
      summary: car
      operationId: car
      tags:
        - car
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
      responses:
        '200':
          description: A car from the database
          schema:
            $ref: '#/definitions/CarDTO'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/Error'
  /delete-car/{id}:
    delete:
      summary: delete car
      operationId: deleteCar
      tags:
        - car
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
      responses:
        '200':
          description: A car from the database
          schema:
            type: boolean
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/Error'
  /update-car/{id}:
    put:
      summary: car
      operationId: updateCar
      tags:
        - car
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
        - in: body
          name: body
          description: operation body
          required: true
          schema:
            $ref: '#/definitions/CarDTO'
      responses:
        '200':
          description: A page of updated car
          schema:
            $ref: '#/definitions/CarDTO'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/Error'
definitions:
  CarListDTO:
    type: array
    items:
      $ref: "#/definitions/CarDTO"
  CarDTO:
    required:
      - id
      - brand
      - model
      - departments
      - rentalOffice
      - petrolType
    properties:
      id:
        type: integer
        format: int64
      brand:
        type: string
      model:
        type: string
      departments:
        $ref: 'departmentSwagger.yaml#/definitions/DepartmentListDTO'
      rentalOffice:
        $ref: 'rentalOfficeSwagger.yaml#/definitions/RentalOfficeDto'
      petrolType:
        enum:
          [DIESEL,
           GASOLINE,
           ELECTRIC]
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string